Add new section to update server xml
OpenLiberty/guide-bean-validation pull request #99
Opened 2021-10-14 15:31 UTC by Kevcpro

2021-10-28 19:01 UTC, gkwan-ibm requested changes
@Kevcpro 
> ...fix the hotspot that it does not highlight the line `<feature>beanValidation-2.0</feature>`

I mean that the `beanValidation` hotspot is needed. In your previous change, it does not work. I expect that you can fix the hotspot to make it work.

2021-10-28 19:07 UTC, gkwan-ibm commented
@Kevcpro 
would you update the following?
- **Programmatically validating constraints**
  - [x] "Finally, create a service..." -> "Next, create a service..."
- **Enabling the Bean Validation feature**
  - [x] "Enable the Bean Validation..." -> "Finally,  add the Bean Validation..."

2021-11-01 20:32 UTC, davidwyao approved these changes

2021-11-01 20:33 UTC, davidwyao approved these changes

2021-11-02 16:20 UTC, dmuelle requested changes
a couple suggestions for concision/ clarity

2021-11-02 16:20 UTC, dmuelle commented on README.adoc
> +Next, create a service that can be used to programmatically validate the constraints
suggested edit:

Next, create a service to programmatically validate the constraints

2021-11-02 16:20 UTC, dmuelle commented on README.adoc
> +The [hotspot=beanValidation file=0]`beanValidation-2.0` feature definition enables the bean validation feature in the
suggested edits

You can now use [hotspot=beanValidation file=0]`beanValidation-2.0` feature  to validate that the supplied JavaBeans meet the defined constraints.

2021-11-03 17:01 UTC, dmuelle approved these changes
LGTM

2021-11-03 21:29 UTC, gkwan-ibm approved these changes

2021-11-25 22:45 UTC, merged